### ISSUE TITLE
How do i exec stark on tf2?

### ISSUE THREAD

**Issue by Solid47** [axynos/STARK#10]
#5 I did every step and i launched tf2 using stark and i opened the console and i typed in "exec stark" and this shows up for me
[https://gyazo.com/1b75fb6da17871e72d4d00a3574e17d1](url)
![nyesss](https://user-images.githubusercontent.com/34064601/33322974-0388a8f0-d486-11e7-9dd5-e59f5df7cb11.png)

please help

**Comment by fuck-shithub** [comment]
The multiple game support is glitched, I fixed it in my fork of Stark, but even on my fork some games won't work (like GMod, but TF2 works fine).

**Comment by Solid47** [comment]
so how do i get it to work on tf2?, do i need like an autoexec type of thing?

**Comment by fuck-shithub** [comment]
just download my fork and read the instructions on the same page
https://github.com/GrimReaperFloof/STARK
