### ISSUE TITLE
Doesn't support custom game directories

### ISSUE THREAD

**Issue by jesterret** [axynos/STARK#5]
If you'd want to support custom directories, you'd have to parse "%SteamPath%/config/config.vdf".
Custom directories have key with this format "BaseInstallFolder_{0}" and you should check whether following file exists "/steamapps/appmanifest_{0}.acf"

**Comment by axynos** [comment]
I'm going to rewrite the game location finder sometime this week probably. This issue is just behind a few others. For now you can set your steamapps to the folder that contains the base path of the game. For exaample: ContainingFolder/common/Counter-Strike... you choose the containingfolder

**Comment by axynos** [comment]
Will be addressed in recode.
