### ISSUE TITLE
Tracklist and text to speech don't work in TF2

### ISSUE THREAD

**Issue by Moffein** [axynos/STARK#6]
s_tracklist always returns a blank list, and the .tts command does not seem to play any text to speech. When checking the /tf/cfg/ folder while Stark and TF2 is running, I noticed that there seem to be no s_play_#.cfg files despite the audio tracks showing up in the Stark menu. 

I can confirm that TF2 is properly logging console output to !!tts-axynos.txt, and the program seems to work fine for CS:GO

**Comment by axynos** [comment]
can you send me a screenshot of the console after trying to use the .tts command in team fortess?

**Comment by Moffein** [comment]
![20161010114750_1](https://cloud.githubusercontent.com/assets/22742925/19247307/6d19ab40-8edf-11e6-87a3-3ece285db1b6.jpg)

**Comment by axynos** [comment]
can you copy-paste that output here?

**Comment by Moffein** [comment]
============ STARK by axynos ============ 
- Available audio tracks: 

# 

owned noob :  .tts hello
owned noob :  .tts 10 seconds have elapsed

**Comment by axynos** [comment]
can you find the location of the logfile in the tf2 folder?

**Comment by Moffein** [comment]
\steamapps\Common\Team Fortress 2\tf\

It's in the root of the \tf\ directory.

**Comment by axynos** [comment]
try going into commandreader and change the logfile from @"!tts-axynos.txt" to @"\tts-axynos.txt"
maybe  tf2 doesn't support special characters

**Comment by Moffein** [comment]
Alright, just did that. Console output and logfile seems to be the same, and s_tracklist + .tts still seem to not work. Works fine when I tested it with CS:GO though.

**Comment by axynos** [comment]
is your watch folder set to where you have audio files?

**Comment by Moffein** [comment]
Yep, they're showing up in the Stark Client.

**Comment by axynos** [comment]
could you paste the contents of the s_tracklist.cfg file here?

**Comment by Moffein** [comment]
In tf/cfg:

clear
echo "============ STARK by axynos ============"
echo ""
echo "   + Available audio tracks:"
echo ""
echo "========================================="

**Comment by axynos** [comment]
is your code on the latest commit?

**Comment by Moffein** [comment]
If you're referring to the fixed game directories and .txt logfile changes, yes.

**Comment by axynos** [comment]
i mean is your code at this commit https://github.com/axynos/STARK/commit/b9d8381fdd27f4ba1e1801500a4fa69b7fab422f

**Comment by Moffein** [comment]
My changes to CommandReader.cs and ConsoleUI.cs there, though the changes to SourceGameManager.cs don't seem to be listed (the changes are there in your source though, as they appear to have been fixed 9 hours ago)

**Comment by axynos** [comment]
Yeah, I merged your pull req before the commit I listed.

**Comment by axynos** [comment]
Could you try re-pulling from the repo?

**Comment by Moffein** [comment]
Sorry for being a bit unfamiliar with these terms, but anyways, would that mean to create a new pull request, or to redownload the source files?

**Comment by axynos** [comment]
I will assume you're using a tool like github for windows or gitkraken. Basically I want you to pull new changes from this repository.

**Comment by Moffein** [comment]
Now I feel silly. I've just been redownloading the sourcefiles every time you make changes. I'll go ahead and install github for windows.

**Comment by Moffein** [comment]
Alright, just did that.

**Comment by axynos** [comment]
and cloned the repo to your comp?

**Comment by Moffein** [comment]
Yep, got it cloned via github and opened in Visual Studio.

**Comment by axynos** [comment]
try running that version and see if it fixed the problem

**Comment by Moffein** [comment]
Just ran it, s_tracklist and .tts still appear to be broken.

**Comment by axynos** [comment]
hmm, a guy just sent me a link to a program quite similar to stark for tf2. They're using voicemeeter. I'll try and take a look at it tomorrow. Would be nice to remove a paid dependency.

**Comment by axynos** [comment]
Will be addressed in recode.
