### ISSUE TITLE
Text to speech synthesises everyone's chat messages

### ISSUE THREAD

**Issue by bhuvan002** [axynos/STARK#7]
Basically, if anyone types ".tss <text>" in the chat, the person using STARK would hear all the messages even if +voicerecord is turned off. Can a feature be implemented such that STARK only synthesises the user's messages? Maybe you could manually input your in game nick in STARK and it would then recognise only your messages?

Cheers

**Comment by axynos** [comment]
Yes, it's a feature I thought of adding before even releaseing the first version. It's on the todo list, but I can't give you a specific timeframe of when it will be implemented.

**Comment by axynos** [comment]
Feature will be added to recode.
